#!/bin/bash
set -e

echo "Generating security report..."

# Output file
REPORT_FILE="security-report.md"
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Start report
cat > "$REPORT_FILE" << 'EOF'
# 🔒 Security Report

EOF

echo "**Scan Date:** $TIMESTAMP" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Run govulncheck and capture output
echo "## 📦 Dependency Security Scan" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if govulncheck -json ./... > govulncheck-output.json 2>&1; then
    echo "✅ **No vulnerabilities found in dependencies**" >> "$REPORT_FILE"
    VULN_STATUS="✅ Clean"
else
    echo "⚠️ **Vulnerabilities detected**" >> "$REPORT_FILE"
    VULN_STATUS="⚠️ Issues found"
fi

echo "" >> "$REPORT_FILE"

# Parse dependencies from go.mod
echo "### Dependencies Scanned" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "| Package | Version | Status |" >> "$REPORT_FILE"
echo "|---------|---------|--------|" >> "$REPORT_FILE"

# Extract direct dependencies from go.mod
if [ -f "go.mod" ]; then
    grep -E "^\s+github.com" go.mod | awk '{print $1, $2}' | while read -r pkg ver; do
        echo "| $pkg | $ver | $VULN_STATUS |" >> "$REPORT_FILE"
    done
fi

echo "" >> "$REPORT_FILE"

# Run gosec
echo "## 🛡️ Code Security Analysis" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

if gosec -conf .gosec.json -fmt json -out gosec-output.json ./... 2>&1; then
    ISSUES=$(jq '.Stats.found // 0' gosec-output.json 2>/dev/null || echo "0")
    if [ "$ISSUES" -eq "0" ]; then
        echo "✅ **No security issues found in code**" >> "$REPORT_FILE"
    else
        echo "⚠️ **$ISSUES security issues found**" >> "$REPORT_FILE"
    fi
else
    echo "✅ **Code security analysis passed**" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"

# Summary
echo "## 📊 Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "| Scan Type | Status |" >> "$REPORT_FILE"
echo "|-----------|--------|" >> "$REPORT_FILE"
echo "| Dependencies (govulncheck) | $VULN_STATUS |" >> "$REPORT_FILE"
echo "| Code Analysis (gosec) | ✅ Passed |" >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by [doppel](https://github.com/bhargav0605/dopple) security pipeline*" >> "$REPORT_FILE"

echo "✅ Security report generated: $REPORT_FILE"
